# Default values for deps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# MQSQL configurations for helm dependency
# you can find more details about this here https://artifacthub.io/packages/helm/bitnami/mysql
mysql:
  enabled: true
  fullnameOverride: "mysql"
  image:
    pullPolicy: "Always"
  auth:
    database: openmetadata_db
    username: "openmetadata_user"
    existingSecret: "mysql-secrets-new"
    rootPassword: password    # provided by CI/CD
  primary:
    service:
      nodePort: 3306
  initdbScripts:
    init_openmetadata_db_scripts.sql: |
      GRANT ALL PRIVILEGES ON openmetadata_db.* TO 'openmetadata_user'@'%' WITH GRANT OPTION;
      commit;
    init_airflow_db_scripts.sql: |
      CREATE DATABASE airflow_db;
      CREATE USER 'airflow_user'@'%' IDENTIFIED BY 'airflow_pass';
      GRANT ALL PRIVILEGES ON airflow_db.* TO 'airflow_user'@'%' WITH GRANT OPTION;
      commit;

# ElasticSearch configurations for helm dependency
# you can find more details about this here https://artifacthub.io/packages/helm/elastic/elasticsearch
elasticsearch:
  enabled: true
  replicas: 1
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  minimumMasterNodes: 1
  fullnameOverride: "elasticsearch"
  imagePullPolicy: "Always"
  esJavaOpts: "-Xmx128m -Xms128m"
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "512M"
